/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ezi_tux4j_GenericClient */

#ifndef _Included_com_ezi_tux4j_GenericClient
#define _Included_com_ezi_tux4j_GenericClient
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ezi_tux4j_GenericClient_PARM_IN
#define com_ezi_tux4j_GenericClient_PARM_IN 1L
#undef com_ezi_tux4j_GenericClient_PARM_OUT
#define com_ezi_tux4j_GenericClient_PARM_OUT 2L
#undef com_ezi_tux4j_GenericClient_PARM_INOUT
#define com_ezi_tux4j_GenericClient_PARM_INOUT 3L
/* Inaccessible static: class_00024com_00024ezi_00024tux4j_00024GenericClient */
/*
 * Class:     com_ezi_tux4j_GenericClient
 * Method:    tuxConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ezi_tux4j_GenericClient_tuxConnect
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_ezi_tux4j_GenericClient
 * Method:    tuxDisconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ezi_tux4j_GenericClient_tuxDisconnect
  (JNIEnv *, jobject);

/*
 * Class:     com_ezi_tux4j_GenericClient
 * Method:    tuxRun
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ezi_tux4j_GenericClient_tuxRun
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ezi_tux4j_GenericClient
 * Method:    bufAddField
 * Signature: (Ljava/lang/String;JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ezi_tux4j_GenericClient_bufAddField
  (JNIEnv *, jobject, jstring, jlong, jstring, jint);

/*
 * Class:     com_ezi_tux4j_GenericClient
 * Method:    bufGetFieldValue
 * Signature: (Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ezi_tux4j_GenericClient_bufGetFieldValue
  (JNIEnv *, jobject, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
